@startuml
'https://plantuml.com/sequence-diagram


actor Sekretarka #blue
actor Szef #black
control Frontend
database Baza #5B1000

autonumber 1

Szef --> Frontend: Podaj listę pracowników
Frontend --> Baza: Zwróć wszystko co masz
Frontend <-- Baza: Lista wszystkich pracowników
Szef <-- Frontend: Lista wszystkich pracowników

autonumber 1

Szef --> Frontend: Lista pracowników wg filtru: F
Frontend --> Baza: Zwróć pracowników wg filtru: F
Frontend <-- Baza: Oto lista pracowników wg filtru: F
Szef <-- Frontend: Lista pracowników wg filtru: F

autonumber 1

Sekretarka --> Frontend: Dodaj pracownika
Frontend --> Baza: Dodaj nowego pracownika o tych danych
Frontend <-- Baza: Dodano pracownika
Sekretarka <-- Frontend: Dodano pracownika

autonumber 1

Sekretarka --> Frontend: Usuń pracownika
Frontend --> Baza: Usuń tego pracownika
Frontend <-- Baza: Usunięto pracownika
Sekretarka <-- Frontend: Usunięto pracownika

autonumber 1

Sekretarka --> Frontend: Edytuj dane pracownika P na dane E
Frontend --> Baza: Podstaw dane pracownika P na dane E
Frontend <-- Baza: Zedytowano dane pracownika P
Sekretarka <-- Frontend: Edycja przebiegła pomyślnie

@enduml