@startuml
'https://plantuml.com/sequence-diagram
class Boss{
    [private]
    String login;
    String haslo;
    list_all();
    list_some();
    getters&setters();
}
class Worker{
    [private]
    int idNum;
    String imie;
    String nazwisko;
    int pesel;
    String obywatelstwo;
    String stanowisko;
    int dni_wolne;
    double wynagrodzenie;
    getters_&_setters();
}
class Secretary{
    worker_add(Worker w);
    worker_del(Worker w);
    worker_edit(Worker w);
    getters_&_setters();
}
class Filter{

}
Secretary o-- Worker
Boss <|-- Secretary
Boss o-- Worker
Boss o-- Filter
@enduml